return {
	["coin1"] = {
		["id"] = "coin1",
		["lv"] = 4,
		["name"] = "晶币",
		["intro"] = "流通货币",
		["source"] = "coin1",
		["delta"] = 0,
	},
	["coin2"] = {
		["id"] = "coin2",
		["lv"] = 5,
		["name"] = "魔石",
		["intro"] = "高级货币",
		["source"] = "coin2",
		["delta"] = 0,
	},
	["coin3"] = {
		["id"] = "coin3",
		["lv"] = 4,
		["name"] = "体力",
		["intro"] = "用于关卡",
		["source"] = "coin3",
		["delta"] = 0,
	},
	["coin4"] = {
		["id"] = "coin4",
		["lv"] = 5,
		["name"] = "四叶草",
		["intro"] = "友情抽卡",
		["source"] = "coin4",
		["delta"] = 0,
	},
	["coin5"] = {
		["id"] = "coin5",
		["lv"] = 5,
		["name"] = "祈愿币",
		["intro"] = "抽士兵&英雄",
		["source"] = "coin5",
		["delta"] = 0,
	},
	["coin6"] = {
		["id"] = "coin6",
		["lv"] = 5,
		["name"] = "狩猎币",
		["intro"] = "抽材料",
		["source"] = "coin6",
		["delta"] = 0,
	},
}
