return {
	["1_1_1_1"] = {
		["id"] = "1_1_1_1",
		["type"] = "equip",
		["name"] = "步兵武器1",
		["source"] = "1_1_1_1",
		["intro"] = "步兵武器1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 1,
		["eq_type"] = 1,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_10",
	},
	["1_1_2_1"] = {
		["id"] = "1_1_2_1",
		["type"] = "equip",
		["name"] = "步兵武器2",
		["source"] = "1_1_2_1",
		["intro"] = "步兵武器2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 1,
		["eq_type"] = 1,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_11",
	},
	["1_1_3_1"] = {
		["id"] = "1_1_3_1",
		["type"] = "equip",
		["name"] = "步兵武器3",
		["source"] = "1_1_3_1",
		["intro"] = "步兵武器3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 1,
		["eq_type"] = 1,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_12",
		["term_id"] = 1,
	},
	["1_1_4_1"] = {
		["id"] = "1_1_4_1",
		["type"] = "equip",
		["name"] = "步兵武器4",
		["source"] = "1_1_4_1",
		["intro"] = "步兵武器4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 1,
		["eq_type"] = 1,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_13",
		["term_id"] = 1,
	},
	["2_1_1_1"] = {
		["id"] = "2_1_1_1",
		["type"] = "equip",
		["name"] = "骑兵武器1",
		["source"] = "2_1_1_1",
		["intro"] = "骑兵武器1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 1,
		["eq_type"] = 2,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_14",
	},
	["2_1_2_1"] = {
		["id"] = "2_1_2_1",
		["type"] = "equip",
		["name"] = "骑兵武器2",
		["source"] = "2_1_2_1",
		["intro"] = "骑兵武器2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 1,
		["eq_type"] = 2,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_15",
	},
	["2_1_3_1"] = {
		["id"] = "2_1_3_1",
		["type"] = "equip",
		["name"] = "骑兵武器3",
		["source"] = "2_1_3_1",
		["intro"] = "骑兵武器3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 1,
		["eq_type"] = 2,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_16",
		["term_id"] = 2,
	},
	["2_1_4_1"] = {
		["id"] = "2_1_4_1",
		["type"] = "equip",
		["name"] = "骑兵武器4",
		["source"] = "2_1_4_1",
		["intro"] = "骑兵武器4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 1,
		["eq_type"] = 2,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_17",
		["term_id"] = 2,
	},
	["3_1_1_1"] = {
		["id"] = "3_1_1_1",
		["type"] = "equip",
		["name"] = "远程武器1",
		["source"] = "3_1_1_1",
		["intro"] = "远程武器1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 1,
		["eq_type"] = 3,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_18",
		["term_id"] = 3,
	},
	["3_1_2_1"] = {
		["id"] = "3_1_2_1",
		["type"] = "equip",
		["name"] = "远程武器2",
		["source"] = "3_1_2_1",
		["intro"] = "远程武器2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 1,
		["eq_type"] = 3,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_19",
	},
	["3_1_3_1"] = {
		["id"] = "3_1_3_1",
		["type"] = "equip",
		["name"] = "远程武器3",
		["source"] = "3_1_3_1",
		["intro"] = "远程武器3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 1,
		["eq_type"] = 3,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_20",
	},
	["3_1_4_1"] = {
		["id"] = "3_1_4_1",
		["type"] = "equip",
		["name"] = "远程武器4",
		["source"] = "3_1_4_1",
		["intro"] = "远程武器4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 1,
		["eq_type"] = 3,
		["attribute_name"] = "atk",
		["attribute_value"] = "6_21",
	},
	["1_2_1_1"] = {
		["id"] = "1_2_1_1",
		["type"] = "equip",
		["name"] = "步兵头盔1",
		["source"] = "1_2_1_1",
		["intro"] = "步兵头盔1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 2,
		["eq_type"] = 1,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_10",
	},
	["1_2_2_1"] = {
		["id"] = "1_2_2_1",
		["type"] = "equip",
		["name"] = "步兵头盔2",
		["source"] = "1_2_2_1",
		["intro"] = "步兵头盔2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 2,
		["eq_type"] = 1,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_11",
		["set_id"] = 2,
	},
	["1_2_3_1"] = {
		["id"] = "1_2_3_1",
		["type"] = "equip",
		["name"] = "步兵头盔3",
		["source"] = "1_2_3_1",
		["intro"] = "步兵头盔3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 2,
		["eq_type"] = 1,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_12",
		["set_id"] = 2,
	},
	["1_2_4_1"] = {
		["id"] = "1_2_4_1",
		["type"] = "equip",
		["name"] = "步兵头盔4",
		["source"] = "1_2_4_1",
		["intro"] = "步兵头盔4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 2,
		["eq_type"] = 1,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_13",
		["set_id"] = 2,
	},
	["2_2_1_1"] = {
		["id"] = "2_2_1_1",
		["type"] = "equip",
		["name"] = "骑兵头盔1",
		["source"] = "2_2_1_1",
		["intro"] = "骑兵头盔1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 2,
		["eq_type"] = 2,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_14",
		["set_id"] = 2,
	},
	["2_2_2_1"] = {
		["id"] = "2_2_2_1",
		["type"] = "equip",
		["name"] = "骑兵头盔2",
		["source"] = "2_2_2_1",
		["intro"] = "骑兵头盔2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 2,
		["eq_type"] = 2,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_15",
	},
	["2_2_3_1"] = {
		["id"] = "2_2_3_1",
		["type"] = "equip",
		["name"] = "骑兵头盔3",
		["source"] = "2_2_3_1",
		["intro"] = "骑兵头盔3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 2,
		["eq_type"] = 2,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_16",
		["set_id"] = 1,
	},
	["2_2_4_1"] = {
		["id"] = "2_2_4_1",
		["type"] = "equip",
		["name"] = "骑兵头盔4",
		["source"] = "2_2_4_1",
		["intro"] = "骑兵头盔4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 2,
		["eq_type"] = 2,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_17",
		["set_id"] = 1,
	},
	["3_2_1_1"] = {
		["id"] = "3_2_1_1",
		["type"] = "equip",
		["name"] = "远程头盔1",
		["source"] = "3_2_1_1",
		["intro"] = "远程头盔1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 2,
		["eq_type"] = 3,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_18",
		["set_id"] = 1,
	},
	["3_2_2_1"] = {
		["id"] = "3_2_2_1",
		["type"] = "equip",
		["name"] = "远程头盔2",
		["source"] = "3_2_2_1",
		["intro"] = "远程头盔2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 2,
		["eq_type"] = 3,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_19",
		["set_id"] = 1,
	},
	["3_2_3_1"] = {
		["id"] = "3_2_3_1",
		["type"] = "equip",
		["name"] = "远程头盔3",
		["source"] = "3_2_3_1",
		["intro"] = "远程头盔3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 2,
		["eq_type"] = 3,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_20",
		["set_id"] = 2,
	},
	["3_2_4_1"] = {
		["id"] = "3_2_4_1",
		["type"] = "equip",
		["name"] = "远程头盔4",
		["source"] = "3_2_4_1",
		["intro"] = "远程头盔4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 2,
		["eq_type"] = 3,
		["attribute_name"] = "hp",
		["attribute_value"] = "6_21",
		["set_id"] = 2,
	},
	["1_3_1_1"] = {
		["id"] = "1_3_1_1",
		["type"] = "equip",
		["name"] = "步兵铠甲1",
		["source"] = "1_3_1_1",
		["intro"] = "步兵铠甲1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 3,
		["eq_type"] = 1,
		["attribute_name"] = "def",
		["attribute_value"] = "6_10",
		["set_id"] = 2,
	},
	["1_3_2_1"] = {
		["id"] = "1_3_2_1",
		["type"] = "equip",
		["name"] = "步兵铠甲2",
		["source"] = "1_3_2_1",
		["intro"] = "步兵铠甲2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 3,
		["eq_type"] = 1,
		["attribute_name"] = "def",
		["attribute_value"] = "6_11",
		["set_id"] = 2,
	},
	["1_3_3_1"] = {
		["id"] = "1_3_3_1",
		["type"] = "equip",
		["name"] = "步兵铠甲3",
		["source"] = "1_3_3_1",
		["intro"] = "步兵铠甲3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 3,
		["eq_type"] = 1,
		["attribute_name"] = "def",
		["attribute_value"] = "6_12",
	},
	["1_3_4_1"] = {
		["id"] = "1_3_4_1",
		["type"] = "equip",
		["name"] = "步兵铠甲4",
		["source"] = "1_3_4_1",
		["intro"] = "步兵铠甲4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 3,
		["eq_type"] = 1,
		["attribute_name"] = "def",
		["attribute_value"] = "6_13",
	},
	["2_3_1_1"] = {
		["id"] = "2_3_1_1",
		["type"] = "equip",
		["name"] = "骑兵铠甲1",
		["source"] = "2_3_1_1",
		["intro"] = "骑兵铠甲1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 3,
		["eq_type"] = 2,
		["attribute_name"] = "def",
		["attribute_value"] = "6_14",
	},
	["2_3_2_1"] = {
		["id"] = "2_3_2_1",
		["type"] = "equip",
		["name"] = "骑兵铠甲2",
		["source"] = "2_3_2_1",
		["intro"] = "骑兵铠甲2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 3,
		["eq_type"] = 2,
		["attribute_name"] = "def",
		["attribute_value"] = "6_15",
	},
	["2_3_3_1"] = {
		["id"] = "2_3_3_1",
		["type"] = "equip",
		["name"] = "骑兵铠甲3",
		["source"] = "2_3_3_1",
		["intro"] = "骑兵铠甲3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 3,
		["eq_type"] = 2,
		["attribute_name"] = "def",
		["attribute_value"] = "6_16",
	},
	["2_3_4_1"] = {
		["id"] = "2_3_4_1",
		["type"] = "equip",
		["name"] = "骑兵铠甲4",
		["source"] = "2_3_4_1",
		["intro"] = "骑兵铠甲4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 3,
		["eq_type"] = 2,
		["attribute_name"] = "def",
		["attribute_value"] = "6_17",
	},
	["3_3_1_1"] = {
		["id"] = "3_3_1_1",
		["type"] = "equip",
		["name"] = "远程铠甲1",
		["source"] = "3_3_1_1",
		["intro"] = "远程铠甲1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 3,
		["eq_type"] = 3,
		["attribute_name"] = "def",
		["attribute_value"] = "6_18",
		["set_id"] = 1,
	},
	["3_3_2_1"] = {
		["id"] = "3_3_2_1",
		["type"] = "equip",
		["name"] = "远程铠甲2",
		["source"] = "3_3_2_1",
		["intro"] = "远程铠甲2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 3,
		["eq_type"] = 3,
		["attribute_name"] = "def",
		["attribute_value"] = "6_19",
		["set_id"] = 1,
	},
	["3_3_3_1"] = {
		["id"] = "3_3_3_1",
		["type"] = "equip",
		["name"] = "远程铠甲3",
		["source"] = "3_3_3_1",
		["intro"] = "远程铠甲3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 3,
		["eq_type"] = 3,
		["attribute_name"] = "def",
		["attribute_value"] = "6_20",
		["set_id"] = 1,
	},
	["3_3_4_1"] = {
		["id"] = "3_3_4_1",
		["type"] = "equip",
		["name"] = "远程铠甲4",
		["source"] = "3_3_4_1",
		["intro"] = "远程铠甲4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 3,
		["eq_type"] = 3,
		["attribute_name"] = "def",
		["attribute_value"] = "6_21",
		["set_id"] = 1,
	},
	["1_4_1_1"] = {
		["id"] = "1_4_1_1",
		["type"] = "equip",
		["name"] = "步兵鞋子1",
		["source"] = "1_4_1_1",
		["intro"] = "步兵鞋子1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 4,
		["eq_type"] = 1,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_10",
		["set_id"] = 2,
	},
	["1_4_2_1"] = {
		["id"] = "1_4_2_1",
		["type"] = "equip",
		["name"] = "步兵鞋子2",
		["source"] = "1_4_2_1",
		["intro"] = "步兵鞋子2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 4,
		["eq_type"] = 1,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_11",
		["set_id"] = 2,
	},
	["1_4_3_1"] = {
		["id"] = "1_4_3_1",
		["type"] = "equip",
		["name"] = "步兵鞋子3",
		["source"] = "1_4_3_1",
		["intro"] = "步兵鞋子3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 4,
		["eq_type"] = 1,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_12",
		["set_id"] = 2,
	},
	["1_4_4_1"] = {
		["id"] = "1_4_4_1",
		["type"] = "equip",
		["name"] = "步兵鞋子4",
		["source"] = "1_4_4_1",
		["intro"] = "步兵鞋子4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 4,
		["eq_type"] = 1,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_13",
		["set_id"] = 2,
	},
	["2_4_1_1"] = {
		["id"] = "2_4_1_1",
		["type"] = "equip",
		["name"] = "骑兵鞋子1",
		["source"] = "2_4_1_1",
		["intro"] = "骑兵鞋子1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 4,
		["eq_type"] = 2,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_14",
	},
	["2_4_2_1"] = {
		["id"] = "2_4_2_1",
		["type"] = "equip",
		["name"] = "骑兵鞋子2",
		["source"] = "2_4_2_1",
		["intro"] = "骑兵鞋子2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 4,
		["eq_type"] = 2,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_15",
		["set_id"] = 1,
	},
	["2_4_3_1"] = {
		["id"] = "2_4_3_1",
		["type"] = "equip",
		["name"] = "骑兵鞋子3",
		["source"] = "2_4_3_1",
		["intro"] = "骑兵鞋子3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 4,
		["eq_type"] = 2,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_16",
		["set_id"] = 1,
	},
	["2_4_4_1"] = {
		["id"] = "2_4_4_1",
		["type"] = "equip",
		["name"] = "骑兵鞋子4",
		["source"] = "2_4_4_1",
		["intro"] = "骑兵鞋子4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 4,
		["eq_type"] = 2,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_17",
		["set_id"] = 1,
	},
	["3_4_1_1"] = {
		["id"] = "3_4_1_1",
		["type"] = "equip",
		["name"] = "远程鞋子1",
		["source"] = "3_4_1_1",
		["intro"] = "远程鞋子1",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 1,
		["eq_slot"] = 4,
		["eq_type"] = 3,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_18",
		["set_id"] = 1,
	},
	["3_4_2_1"] = {
		["id"] = "3_4_2_1",
		["type"] = "equip",
		["name"] = "远程鞋子2",
		["source"] = "3_4_2_1",
		["intro"] = "远程鞋子2",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 2,
		["eq_slot"] = 4,
		["eq_type"] = 3,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_19",
		["set_id"] = 2,
	},
	["3_4_3_1"] = {
		["id"] = "3_4_3_1",
		["type"] = "equip",
		["name"] = "远程鞋子3",
		["source"] = "3_4_3_1",
		["intro"] = "远程鞋子3",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 3,
		["eq_slot"] = 4,
		["eq_type"] = 3,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_20",
		["set_id"] = 2,
	},
	["3_4_4_1"] = {
		["id"] = "3_4_4_1",
		["type"] = "equip",
		["name"] = "远程鞋子4",
		["source"] = "3_4_4_1",
		["intro"] = "远程鞋子4",
		["introduce"] = "很长很长的描述很长很长的描述很长很长的描述很长很长的描述",
		["require"] = {
			[1] = "used",
		},
		["eq_tire"] = 4,
		["eq_slot"] = 4,
		["eq_type"] = 3,
		["attribute_name"] = "speed",
		["attribute_value"] = "6_21",
		["set_id"] = 2,
	},
}
