return {
	["sword_fetter_001"] = {
		["id"] = "sword_fetter_001",
		["major"] = "步兵",
		["type"] = "剑兵",
		["fetter"] = "剑盾共存I",
		["fetter_type"] = "unit",
		["lv"] = 1,
		["intro"] = "当与盾兵并排时，攻击+10，防御+10",
	},
	["sword_fetter_002"] = {
		["id"] = "sword_fetter_002",
		["major"] = "步兵",
		["type"] = "剑兵",
		["fetter"] = "双剑合并",
		["fetter_type"] = "unit_skill",
		["lv"] = 1,
		["intro"] = "当与剑兵并排时，5%概率触发[二连击]",
	},
	["sword_fetter_003"] = {
		["id"] = "sword_fetter_003",
		["major"] = "步兵",
		["type"] = "剑兵",
		["fetter"] = "双剑合并",
		["fetter_type"] = "unit_skill",
		["lv"] = 1,
		["intro"] = "当场上拥有2x2的剑兵阵容，有2%概率触发[剑刃风暴]",
	},
	["fetter_001"] = {
		["id"] = "fetter_001",
		["major"] = "步兵",
		["fetter"] = "步兵荣耀I",
		["fetter_type"] = "type",
		["lv"] = 1,
		["intro"] = "当场上存在3个以上步兵单位则，攻击+10%",
	},
	["fetter_002"] = {
		["id"] = "fetter_002",
		["major"] = "步兵",
		["fetter"] = "步兵荣耀I",
		["fetter_type"] = "type",
		["lv"] = 1,
		["intro"] = "当场上存在6个以上步兵单位则，攻击+25%",
	},
}
