return {
	[1] = {
		["id"] = 1,
		["name"] = "大剑师",
		["first_job"] = "army111",
		["2job_gift"] = "army111:9_1",
		["consum"] = "通用二阶转职书",
	},
	[2] = {
		["id"] = 2,
		["name"] = "精灵剑士",
		["first_job"] = "army111",
		["2job_gift"] = "army111:10_1",
		["consum"] = "特殊二阶转职书",
	},
	[3] = {
		["id"] = 3,
		["name"] = "斧头帮大哥",
		["first_job"] = "army112",
		["consum"] = "特殊二阶转职书",
	},
	[4] = {
		["id"] = 4,
		["name"] = "斧头帮大哥",
		["first_job"] = "army112",
		["consum"] = "特殊二阶转职书",
	},
	[5] = {
		["id"] = 5,
		["name"] = "斧头帮大哥",
		["first_job"] = "army113",
		["consum"] = "特殊二阶转职书",
	},
	[6] = {
		["id"] = 6,
		["name"] = "斧头帮大哥",
		["first_job"] = "army113",
		["consum"] = "特殊二阶转职书",
	},
	[7] = {
		["id"] = 7,
		["name"] = "斧头帮大哥",
		["first_job"] = "army114",
		["consum"] = "特殊二阶转职书",
	},
	[8] = {
		["id"] = 8,
		["name"] = "斧头帮大哥",
		["first_job"] = "army114",
		["consum"] = "特殊二阶转职书",
	},
	[9] = {
		["id"] = 9,
		["name"] = "斧头帮大哥",
		["first_job"] = "army115",
		["consum"] = "特殊二阶转职书",
	},
	[10] = {
		["id"] = 10,
		["name"] = "斧头帮大哥",
		["first_job"] = "army115",
		["consum"] = "特殊二阶转职书",
	},
	[11] = {
		["id"] = 11,
		["name"] = "斧头帮大哥",
		["first_job"] = "army116",
		["consum"] = "特殊二阶转职书",
	},
	[12] = {
		["id"] = 12,
		["name"] = "斧头帮大哥",
		["first_job"] = "army116",
		["consum"] = "特殊二阶转职书",
	},
	[13] = {
		["id"] = 13,
		["name"] = "斧头帮大哥",
		["first_job"] = "army121",
		["consum"] = "特殊二阶转职书",
	},
	[14] = {
		["id"] = 14,
		["name"] = "斧头帮大哥",
		["first_job"] = "army121",
		["consum"] = "特殊二阶转职书",
	},
	[15] = {
		["id"] = 15,
		["name"] = "斧头帮大哥",
		["first_job"] = "army122",
		["consum"] = "特殊二阶转职书",
	},
	[16] = {
		["id"] = 16,
		["name"] = "斧头帮大哥",
		["first_job"] = "army122",
		["consum"] = "特殊二阶转职书",
	},
	[17] = {
		["id"] = 17,
		["name"] = "斧头帮大哥",
		["first_job"] = "army123",
		["consum"] = "特殊二阶转职书",
	},
	[18] = {
		["id"] = 18,
		["name"] = "斧头帮大哥",
		["first_job"] = "army123",
		["consum"] = "特殊二阶转职书",
	},
	[19] = {
		["id"] = 19,
		["name"] = "斧头帮大哥",
		["first_job"] = "army124",
		["consum"] = "特殊二阶转职书",
	},
	[20] = {
		["id"] = 20,
		["name"] = "斧头帮大哥",
		["first_job"] = "army124",
		["consum"] = "特殊二阶转职书",
	},
	[21] = {
		["id"] = 21,
		["name"] = "斧头帮大哥",
		["first_job"] = "army125",
		["consum"] = "特殊二阶转职书",
	},
	[22] = {
		["id"] = 22,
		["name"] = "斧头帮大哥",
		["first_job"] = "army125",
		["consum"] = "特殊二阶转职书",
	},
	[23] = {
		["id"] = 23,
		["name"] = "斧头帮大哥",
		["first_job"] = "army126",
		["consum"] = "特殊二阶转职书",
	},
	[24] = {
		["id"] = 24,
		["name"] = "斧头帮大哥",
		["first_job"] = "army126",
		["consum"] = "特殊二阶转职书",
	},
	[25] = {
		["id"] = 25,
		["name"] = "斧头帮大哥",
		["first_job"] = "army131",
		["consum"] = "特殊二阶转职书",
	},
	[26] = {
		["id"] = 26,
		["name"] = "斧头帮大哥",
		["first_job"] = "army131",
		["consum"] = "特殊二阶转职书",
	},
	[27] = {
		["id"] = 27,
		["name"] = "斧头帮大哥",
		["first_job"] = "army132",
		["consum"] = "特殊二阶转职书",
	},
	[28] = {
		["id"] = 28,
		["name"] = "斧头帮大哥",
		["first_job"] = "army132",
		["consum"] = "特殊二阶转职书",
	},
	[29] = {
		["id"] = 29,
		["name"] = "斧头帮大哥",
		["first_job"] = "army133",
		["consum"] = "特殊二阶转职书",
	},
	[30] = {
		["id"] = 30,
		["name"] = "斧头帮大哥",
		["first_job"] = "army133",
		["consum"] = "特殊二阶转职书",
	},
	[31] = {
		["id"] = 31,
		["name"] = "斧头帮大哥",
		["first_job"] = "army134",
		["consum"] = "特殊二阶转职书",
	},
	[32] = {
		["id"] = 32,
		["name"] = "斧头帮大哥",
		["first_job"] = "army134",
		["consum"] = "特殊二阶转职书",
	},
	[33] = {
		["id"] = 33,
		["name"] = "斧头帮大哥",
		["first_job"] = "army135",
		["consum"] = "特殊二阶转职书",
	},
	[34] = {
		["id"] = 34,
		["name"] = "斧头帮大哥",
		["first_job"] = "army135",
		["consum"] = "特殊二阶转职书",
	},
	[35] = {
		["id"] = 35,
		["name"] = "斧头帮大哥",
		["first_job"] = "army136",
		["consum"] = "特殊二阶转职书",
	},
	[36] = {
		["id"] = 36,
		["name"] = "斧头帮大哥",
		["first_job"] = "army136",
		["consum"] = "特殊二阶转职书",
	},
}
