return {
	["pigraph_001"] = {
		["id"] = "pigraph_001",
		["type"] = "army111",
		["pigraph_type"] = "str",
		["whole"] = 1,
	},
	["pigraph_002"] = {
		["id"] = "pigraph_002",
		["type"] = "army111",
		["pigraph_type"] = "str",
		["whole"] = 2,
	},
	["pigraph_003"] = {
		["id"] = "pigraph_003",
		["type"] = "army111",
		["pigraph_type"] = "str",
		["whole"] = 3,
	},
	["pigraph_004"] = {
		["id"] = "pigraph_004",
		["type"] = "army111",
		["pigraph_type"] = "str",
		["whole"] = 4,
	},
	["pigraph_005"] = {
		["id"] = "pigraph_005",
		["type"] = "army111",
		["pigraph_type"] = "str",
		["whole"] = 5,
	},
	["pigraph_006"] = {
		["id"] = "pigraph_006",
		["type"] = "army111",
		["pigraph_type"] = "str",
		["whole"] = 6,
	},
	["pigraph_007"] = {
		["id"] = "pigraph_007",
		["type"] = "army111",
		["pigraph_type"] = "def",
		["whole"] = 1,
	},
	["pigraph_008"] = {
		["id"] = "pigraph_008",
		["type"] = "army111",
		["pigraph_type"] = "def",
		["whole"] = 2,
	},
	["pigraph_009"] = {
		["id"] = "pigraph_009",
		["type"] = "army111",
		["pigraph_type"] = "def",
		["whole"] = 3,
	},
	["pigraph_010"] = {
		["id"] = "pigraph_010",
		["type"] = "army111",
		["pigraph_type"] = "def",
		["whole"] = 4,
	},
	["pigraph_011"] = {
		["id"] = "pigraph_011",
		["type"] = "army111",
		["pigraph_type"] = "def",
		["whole"] = 5,
	},
	["pigraph_012"] = {
		["id"] = "pigraph_012",
		["type"] = "army111",
		["pigraph_type"] = "def",
		["whole"] = 6,
	},
	["pigraph_013"] = {
		["id"] = "pigraph_013",
		["type"] = "army111",
		["pigraph_type"] = "agi",
		["whole"] = 1,
	},
	["pigraph_014"] = {
		["id"] = "pigraph_014",
		["type"] = "army111",
		["pigraph_type"] = "agi",
		["whole"] = 2,
	},
	["pigraph_015"] = {
		["id"] = "pigraph_015",
		["type"] = "army111",
		["pigraph_type"] = "agi",
		["whole"] = 3,
	},
	["pigraph_016"] = {
		["id"] = "pigraph_016",
		["type"] = "army111",
		["pigraph_type"] = "agi",
		["whole"] = 4,
	},
	["pigraph_017"] = {
		["id"] = "pigraph_017",
		["type"] = "army111",
		["pigraph_type"] = "agi",
		["whole"] = 5,
	},
	["pigraph_018"] = {
		["id"] = "pigraph_018",
		["type"] = "army111",
		["pigraph_type"] = "agi",
		["whole"] = 6,
	},
}
