return {
	["sword_gift_001"] = {
		["id"] = "sword_gift_001",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift"] = "轮回经验I",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "招募剑兵等级+1",
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "250",
			},
		},
	},
	["sword_gift_002"] = {
		["id"] = "sword_gift_002",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift"] = "集中光环I",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "杀敌经验+1%",
	},
	["sword_gift_003"] = {
		["id"] = "sword_gift_003",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift"] = "均衡打击I",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "招募剑兵攻击+1",
	},
	["sword_gift_004"] = {
		["id"] = "sword_gift_004",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift"] = "绝地反击I",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "击杀单位后，+5格挡，持续4s",
	},
	["sword_gift_005"] = {
		["id"] = "sword_gift_005",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift"] = "老兵长谈I",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "周围1个内的所有单位命中+5",
	},
	["sword_gift_006"] = {
		["id"] = "sword_gift_006",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "承载力+1",
	},
	["sword_gift_007"] = {
		["id"] = "sword_gift_007",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "消耗量草-5",
	},
	["sword_gift_008"] = {
		["id"] = "sword_gift_008",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "10%附魔：风属性，转化10%攻击，持续10秒",
	},
	["sword_gift_009"] = {
		["id"] = "sword_gift_009",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "当剑兵遭受超越其生命上限打击时，护甲全消，抵御一次死亡，并释放技能一闪",
	},
	["sword_gift_010"] = {
		["id"] = "sword_gift_010",
		["major"] = "步兵",
		["type"] = "剑兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "10%概率打出【二连击】",
	},
	["sheild_gift_001"] = {
		["id"] = "sheild_gift_001",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "招募盾兵等级+1",
	},
	["sheild_gift_002"] = {
		["id"] = "sheild_gift_002",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "杀敌经验+1%",
	},
	["sheild_gift_003"] = {
		["id"] = "sheild_gift_003",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "承载力+1",
	},
	["sheild_gift_004"] = {
		["id"] = "sheild_gift_004",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
		["intro"] = "格挡反击：格挡成功后对敌人造成0.25s眩晕",
	},
	["sheild_gift_005"] = {
		["id"] = "sheild_gift_005",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["sheild_gift_006"] = {
		["id"] = "sheild_gift_006",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["sheild_gift_007"] = {
		["id"] = "sheild_gift_007",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["sheild_gift_008"] = {
		["id"] = "sheild_gift_008",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["sheild_gift_009"] = {
		["id"] = "sheild_gift_009",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["sheild_gift_010"] = {
		["id"] = "sheild_gift_010",
		["major"] = "步兵",
		["type"] = "盾兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_001"] = {
		["id"] = "axe_gift_001",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_002"] = {
		["id"] = "axe_gift_002",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_003"] = {
		["id"] = "axe_gift_003",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_004"] = {
		["id"] = "axe_gift_004",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_005"] = {
		["id"] = "axe_gift_005",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_006"] = {
		["id"] = "axe_gift_006",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_007"] = {
		["id"] = "axe_gift_007",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_008"] = {
		["id"] = "axe_gift_008",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_009"] = {
		["id"] = "axe_gift_009",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
	["axe_gift_010"] = {
		["id"] = "axe_gift_010",
		["major"] = "步兵",
		["type"] = "斧兵",
		["gift_type"] = "talent",
		["quality"] = 1,
		["lv"] = 1,
		["maxlv"] = 10,
	},
}
