return {
	["army111"] = {
		["id"] = "army111",
		["country"] = 1,
		["type"] = 1,
		["name"] = "剑兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "01",
		["size"] = 0.3,
		["quality"] = 1,
		["atk_distance"] = 1,
		["weak_restraint"] = {
			[1] = {
				[1] = "2",
				[2] = "3",
			},
		},
	},
	["army112"] = {
		["id"] = "army112",
		["country"] = 1,
		["type"] = 1,
		["name"] = "盾兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "02",
		["size"] = 0.3,
		["quality"] = 1,
		["atk_distance"] = 1,
		["weak_restraint"] = {
			[1] = {
				[1] = "2",
				[2] = "3",
			},
		},
	},
	["army113"] = {
		["id"] = "army113",
		["country"] = 1,
		["type"] = 1,
		["name"] = "斧兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "03",
		["size"] = 0.3,
		["quality"] = 2,
		["atk_distance"] = 1,
		["weak_restraint"] = {
			[1] = {
				[1] = "2",
				[2] = "3",
			},
		},
	},
	["army114"] = {
		["id"] = "army114",
		["country"] = 1,
		["type"] = 1,
		["name"] = "枪兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "01",
		["size"] = 0.3,
		["quality"] = 2,
		["atk_distance"] = 1,
		["weak_restraint"] = {
			[1] = {
				[1] = "2",
				[2] = "3",
			},
		},
	},
	["army115"] = {
		["id"] = "army115",
		["country"] = 1,
		["type"] = 1,
		["name"] = "刺客",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "02",
		["size"] = 0.3,
		["quality"] = 3,
		["atk_distance"] = 1,
		["weak_restraint"] = {
			[1] = {
				[1] = "2",
				[2] = "3",
			},
		},
	},
	["army116"] = {
		["id"] = "army116",
		["country"] = 1,
		["type"] = 1,
		["name"] = "狂战士",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "03",
		["size"] = 0.3,
		["quality"] = 3,
		["atk_distance"] = 1,
		["weak_restraint"] = {
			[1] = {
				[1] = "2",
				[2] = "3",
			},
		},
	},
	["army121"] = {
		["id"] = "army121",
		["country"] = 1,
		["type"] = 2,
		["name"] = "刃骑兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "01",
		["size"] = 0.3,
		["quality"] = 1,
		["atk_distance"] = 2,
		["weak_restraint"] = {
			[1] = {
				[1] = "3",
				[2] = "1",
			},
		},
	},
	["army122"] = {
		["id"] = "army122",
		["country"] = 1,
		["type"] = 2,
		["name"] = "枪骑兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "02",
		["size"] = 0.3,
		["quality"] = 1,
		["atk_distance"] = 2,
		["weak_restraint"] = {
			[1] = {
				[1] = "3",
				[2] = "1",
			},
		},
	},
	["army123"] = {
		["id"] = "army123",
		["country"] = 1,
		["type"] = 2,
		["name"] = "镰骑兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "03",
		["size"] = 0.3,
		["quality"] = 2,
		["atk_distance"] = 2,
		["weak_restraint"] = {
			[1] = {
				[1] = "3",
				[2] = "1",
			},
		},
	},
	["army124"] = {
		["id"] = "army124",
		["country"] = 1,
		["type"] = 2,
		["name"] = "轻骑兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "01",
		["size"] = 0.3,
		["quality"] = 2,
		["atk_distance"] = 2,
		["weak_restraint"] = {
			[1] = {
				[1] = "3",
				[2] = "1",
			},
		},
	},
	["army125"] = {
		["id"] = "army125",
		["country"] = 1,
		["type"] = 2,
		["name"] = "重骑兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "02",
		["size"] = 0.3,
		["quality"] = 3,
		["atk_distance"] = 2,
		["weak_restraint"] = {
			[1] = {
				[1] = "3",
				[2] = "1",
			},
		},
	},
	["army126"] = {
		["id"] = "army126",
		["country"] = 1,
		["type"] = 2,
		["name"] = "大地骑士",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "03",
		["size"] = 0.3,
		["quality"] = 3,
		["atk_distance"] = 2,
		["weak_restraint"] = {
			[1] = {
				[1] = "3",
				[2] = "1",
			},
		},
	},
	["army131"] = {
		["id"] = "army131",
		["country"] = 1,
		["type"] = 3,
		["name"] = "弓兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "01",
		["size"] = 0.3,
		["quality"] = 1,
		["atk_distance"] = 10,
		["weak_restraint"] = {
			[1] = {
				[1] = "1",
				[2] = "2",
			},
		},
	},
	["army132"] = {
		["id"] = "army132",
		["country"] = 1,
		["type"] = 3,
		["name"] = "弩兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "02",
		["size"] = 0.3,
		["quality"] = 1,
		["atk_distance"] = 10,
		["weak_restraint"] = {
			[1] = {
				[1] = "1",
				[2] = "2",
			},
		},
	},
	["army133"] = {
		["id"] = "army133",
		["country"] = 1,
		["type"] = 3,
		["name"] = "枪兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "03",
		["size"] = 0.3,
		["quality"] = 2,
		["atk_distance"] = 10,
		["weak_restraint"] = {
			[1] = {
				[1] = "1",
				[2] = "2",
			},
		},
	},
	["army134"] = {
		["id"] = "army134",
		["country"] = 1,
		["type"] = 3,
		["name"] = "炮兵",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "01",
		["size"] = 0.3,
		["quality"] = 2,
		["atk_distance"] = 10,
		["weak_restraint"] = {
			[1] = {
				[1] = "1",
				[2] = "2",
			},
		},
	},
	["army135"] = {
		["id"] = "army135",
		["country"] = 1,
		["type"] = 3,
		["name"] = "攻城器",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "02",
		["size"] = 0.3,
		["quality"] = 3,
		["atk_distance"] = 10,
		["weak_restraint"] = {
			[1] = {
				[1] = "1",
				[2] = "2",
			},
		},
	},
	["army136"] = {
		["id"] = "army136",
		["country"] = 1,
		["type"] = 3,
		["name"] = "旋刃猎手",
		["res_spine"] = "hero1",
		["res_card"] = "test01",
		["skin"] = "03",
		["size"] = 0.3,
		["quality"] = 3,
		["atk_distance"] = 10,
		["weak_restraint"] = {
			[1] = {
				[1] = "1",
				[2] = "2",
			},
		},
	},
}
