return {
	["sword_star_in_011"] = {
		["id"] = "sword_star_in_011",
		["type"] = "剑兵",
		["name"] = "实习剑士",
		["star"] = 1,
	},
	["sword_star_in_021"] = {
		["id"] = "sword_star_in_021",
		["type"] = "剑兵",
		["name"] = "预备剑士",
		["star"] = 2,
		["combine"] = {
			[1] = {
				[1] = "sword_star_001",
				[2] = "3",
			},
		},
	},
	["sword_star_in_031"] = {
		["id"] = "sword_star_in_031",
		["type"] = "剑兵",
		["name"] = "初阶剑士",
		["star"] = 3,
		["combine"] = {
			[1] = {
				[1] = "sword_star_002",
				[2] = "3",
			},
		},
	},
	["sword_star_in_041"] = {
		["id"] = "sword_star_in_041",
		["type"] = "剑兵",
		["name"] = "中阶剑士",
		["star"] = 4,
		["combine"] = {
			[1] = {
				[1] = "sword_star_003",
				[2] = "3",
			},
		},
	},
	["sword_star_in_051"] = {
		["id"] = "sword_star_in_051",
		["type"] = "剑兵",
		["name"] = "高阶剑士",
		["star"] = 5,
		["combine"] = {
			[1] = {
				[1] = "sword_star_004",
				[2] = "3",
			},
		},
	},
	["sheild_star_in_011"] = {
		["id"] = "sheild_star_in_011",
		["type"] = "盾兵",
		["name"] = "实习盾兵",
		["star"] = 1,
	},
	["sheild_star_in_012"] = {
		["id"] = "sheild_star_in_012",
		["type"] = "盾兵",
		["name"] = "预备盾兵",
		["star"] = 2,
	},
	["sheild_star_in_013"] = {
		["id"] = "sheild_star_in_013",
		["type"] = "盾兵",
		["name"] = "初阶盾兵",
		["star"] = 3,
	},
	["sheild_star_in_014"] = {
		["id"] = "sheild_star_in_014",
		["type"] = "盾兵",
		["name"] = "中阶盾兵",
		["star"] = 4,
	},
	["sheild_star_in_015"] = {
		["id"] = "sheild_star_in_015",
		["type"] = "盾兵",
		["name"] = "高阶盾兵",
		["star"] = 5,
	},
	["axe_star_in_011"] = {
		["id"] = "axe_star_in_011",
		["type"] = "斧兵",
		["name"] = "实习斧兵",
		["star"] = 1,
	},
	["axe_star_in_012"] = {
		["id"] = "axe_star_in_012",
		["type"] = "斧兵",
		["name"] = "预备斧兵",
		["star"] = 2,
	},
	["axe_star_in_013"] = {
		["id"] = "axe_star_in_013",
		["type"] = "斧兵",
		["name"] = "初阶斧兵",
		["star"] = 3,
	},
	["axe_star_in_014"] = {
		["id"] = "axe_star_in_014",
		["type"] = "斧兵",
		["name"] = "中阶斧兵",
		["star"] = 4,
	},
	["axe_star_in_015"] = {
		["id"] = "axe_star_in_015",
		["type"] = "斧兵",
		["name"] = "高阶斧兵",
		["star"] = 5,
	},
	["spear_star_in_011"] = {
		["id"] = "spear_star_in_011",
		["type"] = "枪兵",
		["name"] = "实习枪兵",
		["star"] = 1,
	},
	["spear_star_in_012"] = {
		["id"] = "spear_star_in_012",
		["type"] = "枪兵",
		["name"] = "预备枪兵",
		["star"] = 2,
	},
	["spear_star_in_013"] = {
		["id"] = "spear_star_in_013",
		["type"] = "枪兵",
		["name"] = "初阶枪兵",
		["star"] = 3,
	},
	["spear_star_in_014"] = {
		["id"] = "spear_star_in_014",
		["type"] = "枪兵",
		["name"] = "中阶枪兵",
		["star"] = 4,
	},
	["spear_star_in_015"] = {
		["id"] = "spear_star_in_015",
		["type"] = "枪兵",
		["name"] = "高阶枪兵",
		["star"] = 5,
	},
	["assassin_star_in_011"] = {
		["id"] = "assassin_star_in_011",
		["type"] = "刺客",
		["name"] = "实习刺客",
		["star"] = 1,
	},
	["assassin_star_in_012"] = {
		["id"] = "assassin_star_in_012",
		["type"] = "刺客",
		["name"] = "预备刺客",
		["star"] = 2,
	},
	["assassin_star_in_013"] = {
		["id"] = "assassin_star_in_013",
		["type"] = "刺客",
		["name"] = "初阶刺客",
		["star"] = 3,
	},
	["assassin_star_in_014"] = {
		["id"] = "assassin_star_in_014",
		["type"] = "刺客",
		["name"] = "中阶刺客",
		["star"] = 4,
	},
	["assassin_star_in_015"] = {
		["id"] = "assassin_star_in_015",
		["type"] = "刺客",
		["name"] = "高阶刺客",
		["star"] = 5,
	},
	["berserker_star_in_011"] = {
		["id"] = "berserker_star_in_011",
		["type"] = "狂战士",
		["name"] = "实习狂战士",
		["star"] = 1,
	},
	["berserker_star_in_012"] = {
		["id"] = "berserker_star_in_012",
		["type"] = "狂战士",
		["name"] = "预备狂战士",
		["star"] = 2,
	},
	["berserker_star_in_013"] = {
		["id"] = "berserker_star_in_013",
		["type"] = "狂战士",
		["name"] = "初阶狂战士",
		["star"] = 3,
	},
	["berserker_star_in_014"] = {
		["id"] = "berserker_star_in_014",
		["type"] = "狂战士",
		["name"] = "中阶狂战士",
		["star"] = 4,
	},
	["berserker_star_in_015"] = {
		["id"] = "berserker_star_in_015",
		["type"] = "狂战士",
		["name"] = "高阶狂战士",
		["star"] = 5,
	},
	["blade_rider_star_in_011"] = {
		["id"] = "blade_rider_star_in_011",
		["type"] = "刃骑兵",
		["name"] = "实习刃骑兵",
		["star"] = 1,
	},
	["blade_rider_star_in_012"] = {
		["id"] = "blade_rider_star_in_012",
		["type"] = "刃骑兵",
		["name"] = "预备刃骑兵",
		["star"] = 2,
	},
	["blade_rider_star_in_013"] = {
		["id"] = "blade_rider_star_in_013",
		["type"] = "刃骑兵",
		["name"] = "初阶刃骑兵",
		["star"] = 3,
	},
	["blade_rider_star_in_014"] = {
		["id"] = "blade_rider_star_in_014",
		["type"] = "刃骑兵",
		["name"] = "中阶刃骑兵",
		["star"] = 4,
	},
	["blade_rider_star_in_015"] = {
		["id"] = "blade_rider_star_in_015",
		["type"] = "刃骑兵",
		["name"] = "高阶刃骑兵",
		["star"] = 5,
	},
	["lancer_star_in_011"] = {
		["id"] = "lancer_star_in_011",
		["type"] = "枪骑兵",
		["name"] = "实习枪骑兵",
		["star"] = 1,
	},
	["lancer_star_in_012"] = {
		["id"] = "lancer_star_in_012",
		["type"] = "枪骑兵",
		["name"] = "预备枪骑兵",
		["star"] = 2,
	},
	["lancer_star_in_013"] = {
		["id"] = "lancer_star_in_013",
		["type"] = "枪骑兵",
		["name"] = "初阶枪骑兵",
		["star"] = 3,
	},
	["lancer_star_in_014"] = {
		["id"] = "lancer_star_in_014",
		["type"] = "枪骑兵",
		["name"] = "中阶枪骑兵",
		["star"] = 4,
	},
	["lancer_star_in_015"] = {
		["id"] = "lancer_star_in_015",
		["type"] = "枪骑兵",
		["name"] = "高阶枪骑兵",
		["star"] = 5,
	},
	["scythe_rider_star_in_011"] = {
		["id"] = "scythe_rider_star_in_011",
		["type"] = "镰骑兵",
		["name"] = "实习镰骑兵",
		["star"] = 1,
	},
	["scythe_rider_star_in_012"] = {
		["id"] = "scythe_rider_star_in_012",
		["type"] = "镰骑兵",
		["name"] = "预备镰骑兵",
		["star"] = 2,
	},
	["scythe_rider_star_in_013"] = {
		["id"] = "scythe_rider_star_in_013",
		["type"] = "镰骑兵",
		["name"] = "初阶镰骑兵",
		["star"] = 3,
	},
	["scythe_rider_star_in_014"] = {
		["id"] = "scythe_rider_star_in_014",
		["type"] = "镰骑兵",
		["name"] = "中阶镰骑兵",
		["star"] = 4,
	},
	["scythe_rider_star_in_015"] = {
		["id"] = "scythe_rider_star_in_015",
		["type"] = "镰骑兵",
		["name"] = "高阶镰骑兵",
		["star"] = 5,
	},
	["hussar_star_in_011"] = {
		["id"] = "hussar_star_in_011",
		["type"] = "轻骑兵",
		["name"] = "实习轻骑兵",
		["star"] = 1,
	},
	["hussar_star_in_012"] = {
		["id"] = "hussar_star_in_012",
		["type"] = "轻骑兵",
		["name"] = "预备轻骑兵",
		["star"] = 2,
	},
	["hussar_star_in_013"] = {
		["id"] = "hussar_star_in_013",
		["type"] = "轻骑兵",
		["name"] = "初阶轻骑兵",
		["star"] = 3,
	},
	["hussar_star_in_014"] = {
		["id"] = "hussar_star_in_014",
		["type"] = "轻骑兵",
		["name"] = "中阶轻骑兵",
		["star"] = 4,
	},
	["hussar_star_in_015"] = {
		["id"] = "hussar_star_in_015",
		["type"] = "轻骑兵",
		["name"] = "高阶轻骑兵",
		["star"] = 5,
	},
	["heavy_rider_star_in_011"] = {
		["id"] = "heavy_rider_star_in_011",
		["type"] = "重骑兵",
		["name"] = "实习重骑兵",
		["star"] = 1,
	},
	["heavy_rider_star_in_012"] = {
		["id"] = "heavy_rider_star_in_012",
		["type"] = "重骑兵",
		["name"] = "预备重骑兵",
		["star"] = 2,
	},
	["heavy_rider_star_in_013"] = {
		["id"] = "heavy_rider_star_in_013",
		["type"] = "重骑兵",
		["name"] = "初阶重骑兵",
		["star"] = 3,
	},
	["heavy_rider_star_in_014"] = {
		["id"] = "heavy_rider_star_in_014",
		["type"] = "重骑兵",
		["name"] = "中阶重骑兵",
		["star"] = 4,
	},
	["heavy_rider_star_in_015"] = {
		["id"] = "heavy_rider_star_in_015",
		["type"] = "重骑兵",
		["name"] = "高阶重骑兵",
		["star"] = 5,
	},
	["earth_rider_star_in_011"] = {
		["id"] = "earth_rider_star_in_011",
		["type"] = "大地骑士",
		["name"] = "实习大地骑士",
		["star"] = 1,
	},
	["earth_rider_star_in_012"] = {
		["id"] = "earth_rider_star_in_012",
		["type"] = "大地骑士",
		["name"] = "预备大地骑士",
		["star"] = 2,
	},
	["earth_rider_star_in_013"] = {
		["id"] = "earth_rider_star_in_013",
		["type"] = "大地骑士",
		["name"] = "初阶大地骑士",
		["star"] = 3,
	},
	["earth_rider_star_in_014"] = {
		["id"] = "earth_rider_star_in_014",
		["type"] = "大地骑士",
		["name"] = "中阶大地骑士",
		["star"] = 4,
	},
	["earth_rider_star_in_015"] = {
		["id"] = "earth_rider_star_in_015",
		["type"] = "大地骑士",
		["name"] = "高阶大地骑士",
		["star"] = 5,
	},
	["bowmen_star_in_011"] = {
		["id"] = "bowmen_star_in_011",
		["type"] = "弓兵",
		["name"] = "实习弓兵",
		["star"] = 1,
	},
	["bowmen_star_in_012"] = {
		["id"] = "bowmen_star_in_012",
		["type"] = "弓兵",
		["name"] = "预备弓兵",
		["star"] = 2,
	},
	["bowmen_star_in_013"] = {
		["id"] = "bowmen_star_in_013",
		["type"] = "弓兵",
		["name"] = "初阶弓兵",
		["star"] = 3,
	},
	["bowmen_star_in_014"] = {
		["id"] = "bowmen_star_in_014",
		["type"] = "弓兵",
		["name"] = "中阶弓兵",
		["star"] = 4,
	},
	["bowmen_star_in_015"] = {
		["id"] = "bowmen_star_in_015",
		["type"] = "弓兵",
		["name"] = "高阶弓兵",
		["star"] = 5,
	},
	["crossbowman_star_in_011"] = {
		["id"] = "crossbowman_star_in_011",
		["type"] = "弩兵",
		["name"] = "实习弩兵",
		["star"] = 1,
	},
	["crossbowman_star_in_012"] = {
		["id"] = "crossbowman_star_in_012",
		["type"] = "弩兵",
		["name"] = "预备弩兵",
		["star"] = 2,
	},
	["crossbowman_star_in_013"] = {
		["id"] = "crossbowman_star_in_013",
		["type"] = "弩兵",
		["name"] = "初阶弩兵",
		["star"] = 3,
	},
	["crossbowman_star_in_014"] = {
		["id"] = "crossbowman_star_in_014",
		["type"] = "弩兵",
		["name"] = "中阶弩兵",
		["star"] = 4,
	},
	["crossbowman_star_in_015"] = {
		["id"] = "crossbowman_star_in_015",
		["type"] = "弩兵",
		["name"] = "高阶弩兵",
		["star"] = 5,
	},
	["musketeer_star_in_011"] = {
		["id"] = "musketeer_star_in_011",
		["type"] = "火枪兵",
		["name"] = "实习火枪兵",
		["star"] = 1,
	},
	["musketeer_star_in_012"] = {
		["id"] = "musketeer_star_in_012",
		["type"] = "火枪兵",
		["name"] = "预备火枪兵",
		["star"] = 2,
	},
	["musketeer_star_in_013"] = {
		["id"] = "musketeer_star_in_013",
		["type"] = "火枪兵",
		["name"] = "初阶火枪兵",
		["star"] = 3,
	},
	["musketeer_star_in_014"] = {
		["id"] = "musketeer_star_in_014",
		["type"] = "火枪兵",
		["name"] = "中阶火枪兵",
		["star"] = 4,
	},
	["musketeer_star_in_015"] = {
		["id"] = "musketeer_star_in_015",
		["type"] = "火枪兵",
		["name"] = "高阶火枪兵",
		["star"] = 5,
	},
	["artillery_star_in_011"] = {
		["id"] = "artillery_star_in_011",
		["type"] = "炮兵",
		["name"] = "实习炮兵",
		["star"] = 1,
	},
	["artillery_star_in_012"] = {
		["id"] = "artillery_star_in_012",
		["type"] = "炮兵",
		["name"] = "预备炮兵",
		["star"] = 2,
	},
	["artillery_star_in_013"] = {
		["id"] = "artillery_star_in_013",
		["type"] = "炮兵",
		["name"] = "初阶炮兵",
		["star"] = 3,
	},
	["artillery_star_in_014"] = {
		["id"] = "artillery_star_in_014",
		["type"] = "炮兵",
		["name"] = "中阶炮兵",
		["star"] = 4,
	},
	["artillery_star_in_015"] = {
		["id"] = "artillery_star_in_015",
		["type"] = "炮兵",
		["name"] = "高阶炮兵",
		["star"] = 5,
	},
	["siege_star_in_011"] = {
		["id"] = "siege_star_in_011",
		["type"] = "攻城器",
		["name"] = "实习攻城器",
		["star"] = 1,
	},
	["siege_star_in_012"] = {
		["id"] = "siege_star_in_012",
		["type"] = "攻城器",
		["name"] = "预备攻城器",
		["star"] = 2,
	},
	["siege_star_in_013"] = {
		["id"] = "siege_star_in_013",
		["type"] = "攻城器",
		["name"] = "初阶攻城器",
		["star"] = 3,
	},
	["siege_star_in_014"] = {
		["id"] = "siege_star_in_014",
		["type"] = "攻城器",
		["name"] = "中阶攻城器",
		["star"] = 4,
	},
	["siege_star_in_015"] = {
		["id"] = "siege_star_in_015",
		["type"] = "攻城器",
		["name"] = "高阶攻城器",
		["star"] = 5,
	},
	["blade_hunter_star_in_011"] = {
		["id"] = "blade_hunter_star_in_011",
		["type"] = "旋刃猎手",
		["name"] = "实习旋刃猎手",
		["star"] = 1,
	},
	["blade_hunter_star_in_012"] = {
		["id"] = "blade_hunter_star_in_012",
		["type"] = "旋刃猎手",
		["name"] = "预备旋刃猎手",
		["star"] = 2,
	},
	["blade_hunter_star_in_013"] = {
		["id"] = "blade_hunter_star_in_013",
		["type"] = "旋刃猎手",
		["name"] = "初阶旋刃猎手",
		["star"] = 3,
	},
	["blade_hunter_star_in_014"] = {
		["id"] = "blade_hunter_star_in_014",
		["type"] = "旋刃猎手",
		["name"] = "中阶旋刃猎手",
		["star"] = 4,
	},
	["blade_hunter_star_in_015"] = {
		["id"] = "blade_hunter_star_in_015",
		["type"] = "旋刃猎手",
		["name"] = "高阶旋刃猎手",
		["star"] = 5,
	},
}
