return {
	["sword_star_out_011"] = {
		["id"] = "sword_star_out_011",
		["type"] = "剑兵",
		["name"] = "实习剑士",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "100",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_012"] = {
		["id"] = "sword_star_out_012",
		["type"] = "剑兵",
		["name"] = "实习剑士",
		["star"] = 1,
		["stage"] = 2,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "101",
			},
		},
		["atk_coe"] = 1.224,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_013"] = {
		["id"] = "sword_star_out_013",
		["type"] = "剑兵",
		["name"] = "实习剑士",
		["star"] = 1,
		["stage"] = 3,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "102",
			},
		},
		["atk_coe"] = 1.228,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_014"] = {
		["id"] = "sword_star_out_014",
		["type"] = "剑兵",
		["name"] = "实习剑士",
		["star"] = 1,
		["stage"] = 4,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "103",
			},
		},
		["atk_coe"] = 1.232,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_015"] = {
		["id"] = "sword_star_out_015",
		["type"] = "剑兵",
		["name"] = "实习剑士",
		["star"] = 1,
		["stage"] = 5,
		["exp"] = 4500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "104",
			},
		},
		["atk_coe"] = 1.236,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_002"] = {
		["id"] = "sword_star_out_002",
		["type"] = "剑兵",
		["name"] = "预备剑士",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "105",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_003"] = {
		["id"] = "sword_star_out_003",
		["type"] = "剑兵",
		["name"] = "初阶剑士",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "106",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_004"] = {
		["id"] = "sword_star_out_004",
		["type"] = "剑兵",
		["name"] = "中阶剑士",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "107",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["sword_star_out_005"] = {
		["id"] = "sword_star_out_005",
		["type"] = "剑兵",
		["name"] = "高阶剑士",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "108",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["sheild_star_out_011"] = {
		["id"] = "sheild_star_out_011",
		["type"] = "盾兵",
		["name"] = "实习盾兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "109",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["sheild_star_out_021"] = {
		["id"] = "sheild_star_out_021",
		["type"] = "盾兵",
		["name"] = "预备盾兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "110",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["sheild_star_out_031"] = {
		["id"] = "sheild_star_out_031",
		["type"] = "盾兵",
		["name"] = "初阶盾兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "111",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["sheild_star_out_041"] = {
		["id"] = "sheild_star_out_041",
		["type"] = "盾兵",
		["name"] = "中阶盾兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "112",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["sheild_star_out_051"] = {
		["id"] = "sheild_star_out_051",
		["type"] = "盾兵",
		["name"] = "高阶盾兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "113",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["axe_star_out_011"] = {
		["id"] = "axe_star_out_011",
		["type"] = "斧兵",
		["name"] = "实习斧兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "114",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["axe_star_out_021"] = {
		["id"] = "axe_star_out_021",
		["type"] = "斧兵",
		["name"] = "预备斧兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "115",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["axe_star_out_031"] = {
		["id"] = "axe_star_out_031",
		["type"] = "斧兵",
		["name"] = "初阶斧兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "116",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["axe_star_out_041"] = {
		["id"] = "axe_star_out_041",
		["type"] = "斧兵",
		["name"] = "中阶斧兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "117",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["axe_star_out_051"] = {
		["id"] = "axe_star_out_051",
		["type"] = "斧兵",
		["name"] = "高阶斧兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "118",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["spear_star_out_011"] = {
		["id"] = "spear_star_out_011",
		["type"] = "枪兵",
		["name"] = "实习枪兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "119",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["spear_star_out_021"] = {
		["id"] = "spear_star_out_021",
		["type"] = "枪兵",
		["name"] = "预备枪兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "120",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["spear_star_out_031"] = {
		["id"] = "spear_star_out_031",
		["type"] = "枪兵",
		["name"] = "初阶枪兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "121",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["spear_star_out_041"] = {
		["id"] = "spear_star_out_041",
		["type"] = "枪兵",
		["name"] = "中阶枪兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "122",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["spear_star_out_051"] = {
		["id"] = "spear_star_out_051",
		["type"] = "枪兵",
		["name"] = "高阶枪兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "123",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["assassin_star_out_011"] = {
		["id"] = "assassin_star_out_011",
		["type"] = "刺客",
		["name"] = "实习刺客",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "124",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["assassin_star_out_021"] = {
		["id"] = "assassin_star_out_021",
		["type"] = "刺客",
		["name"] = "预备刺客",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "125",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["assassin_star_out_031"] = {
		["id"] = "assassin_star_out_031",
		["type"] = "刺客",
		["name"] = "初阶刺客",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "126",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["assassin_star_out_041"] = {
		["id"] = "assassin_star_out_041",
		["type"] = "刺客",
		["name"] = "中阶刺客",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "127",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["assassin_star_out_051"] = {
		["id"] = "assassin_star_out_051",
		["type"] = "刺客",
		["name"] = "高阶刺客",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "128",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["berserker_star_out_011"] = {
		["id"] = "berserker_star_out_011",
		["type"] = "狂战士",
		["name"] = "实习狂战士",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "129",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["berserker_star_out_021"] = {
		["id"] = "berserker_star_out_021",
		["type"] = "狂战士",
		["name"] = "预备狂战士",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "130",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["berserker_star_out_031"] = {
		["id"] = "berserker_star_out_031",
		["type"] = "狂战士",
		["name"] = "初阶狂战士",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "131",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["berserker_star_out_041"] = {
		["id"] = "berserker_star_out_041",
		["type"] = "狂战士",
		["name"] = "中阶狂战士",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "132",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["berserker_star_out_051"] = {
		["id"] = "berserker_star_out_051",
		["type"] = "狂战士",
		["name"] = "高阶狂战士",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "133",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["blade_rider_star_out_011"] = {
		["id"] = "blade_rider_star_out_011",
		["type"] = "刃骑兵",
		["name"] = "实习刃骑兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "134",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["blade_rider_star_out_021"] = {
		["id"] = "blade_rider_star_out_021",
		["type"] = "刃骑兵",
		["name"] = "预备刃骑兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "135",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["blade_rider_star_out_031"] = {
		["id"] = "blade_rider_star_out_031",
		["type"] = "刃骑兵",
		["name"] = "初阶刃骑兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "136",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["blade_rider_star_out_041"] = {
		["id"] = "blade_rider_star_out_041",
		["type"] = "刃骑兵",
		["name"] = "中阶刃骑兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "137",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["blade_rider_star_out_051"] = {
		["id"] = "blade_rider_star_out_051",
		["type"] = "刃骑兵",
		["name"] = "高阶刃骑兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "138",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["lancer_star_out_011"] = {
		["id"] = "lancer_star_out_011",
		["type"] = "枪骑兵",
		["name"] = "实习枪骑兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "139",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["lancer_star_out_021"] = {
		["id"] = "lancer_star_out_021",
		["type"] = "枪骑兵",
		["name"] = "预备枪骑兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "140",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["lancer_star_out_031"] = {
		["id"] = "lancer_star_out_031",
		["type"] = "枪骑兵",
		["name"] = "初阶枪骑兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "141",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["lancer_star_out_041"] = {
		["id"] = "lancer_star_out_041",
		["type"] = "枪骑兵",
		["name"] = "中阶枪骑兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "142",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["lancer_star_out_051"] = {
		["id"] = "lancer_star_out_051",
		["type"] = "枪骑兵",
		["name"] = "高阶枪骑兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "143",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["scythe_rider_star_out_011"] = {
		["id"] = "scythe_rider_star_out_011",
		["type"] = "镰骑兵",
		["name"] = "实习镰骑兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "144",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["scythe_rider_star_out_021"] = {
		["id"] = "scythe_rider_star_out_021",
		["type"] = "镰骑兵",
		["name"] = "预备镰骑兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "145",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["scythe_rider_star_out_031"] = {
		["id"] = "scythe_rider_star_out_031",
		["type"] = "镰骑兵",
		["name"] = "初阶镰骑兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "146",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["scythe_rider_star_out_041"] = {
		["id"] = "scythe_rider_star_out_041",
		["type"] = "镰骑兵",
		["name"] = "中阶镰骑兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "147",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["scythe_rider_star_out_051"] = {
		["id"] = "scythe_rider_star_out_051",
		["type"] = "镰骑兵",
		["name"] = "高阶镰骑兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "148",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["hussar_star_out_011"] = {
		["id"] = "hussar_star_out_011",
		["type"] = "轻骑兵",
		["name"] = "实习轻骑兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "149",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["hussar_star_out_021"] = {
		["id"] = "hussar_star_out_021",
		["type"] = "轻骑兵",
		["name"] = "预备轻骑兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "150",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["hussar_star_out_031"] = {
		["id"] = "hussar_star_out_031",
		["type"] = "轻骑兵",
		["name"] = "初阶轻骑兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "151",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["hussar_star_out_041"] = {
		["id"] = "hussar_star_out_041",
		["type"] = "轻骑兵",
		["name"] = "中阶轻骑兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "152",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["hussar_star_out_051"] = {
		["id"] = "hussar_star_out_051",
		["type"] = "轻骑兵",
		["name"] = "高阶轻骑兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "153",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["heavy_rider_star_out_011"] = {
		["id"] = "heavy_rider_star_out_011",
		["type"] = "重骑兵",
		["name"] = "实习重骑兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "154",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["heavy_rider_star_out_021"] = {
		["id"] = "heavy_rider_star_out_021",
		["type"] = "重骑兵",
		["name"] = "预备重骑兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "155",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["heavy_rider_star_out_031"] = {
		["id"] = "heavy_rider_star_out_031",
		["type"] = "重骑兵",
		["name"] = "初阶重骑兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "156",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["heavy_rider_star_out_041"] = {
		["id"] = "heavy_rider_star_out_041",
		["type"] = "重骑兵",
		["name"] = "中阶重骑兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "157",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["heavy_rider_star_out_051"] = {
		["id"] = "heavy_rider_star_out_051",
		["type"] = "重骑兵",
		["name"] = "高阶重骑兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "158",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["earth_rider_star_out_011"] = {
		["id"] = "earth_rider_star_out_011",
		["type"] = "大地骑士",
		["name"] = "实习大地骑士",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "159",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["earth_rider_star_out_021"] = {
		["id"] = "earth_rider_star_out_021",
		["type"] = "大地骑士",
		["name"] = "预备大地骑士",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "160",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["earth_rider_star_out_031"] = {
		["id"] = "earth_rider_star_out_031",
		["type"] = "大地骑士",
		["name"] = "初阶大地骑士",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "161",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["earth_rider_star_out_041"] = {
		["id"] = "earth_rider_star_out_041",
		["type"] = "大地骑士",
		["name"] = "中阶大地骑士",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "162",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["earth_rider_star_out_051"] = {
		["id"] = "earth_rider_star_out_051",
		["type"] = "大地骑士",
		["name"] = "高阶大地骑士",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "163",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["bowmen_star_out_011"] = {
		["id"] = "bowmen_star_out_011",
		["type"] = "弓兵",
		["name"] = "实习弓兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "164",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["bowmen_star_out_021"] = {
		["id"] = "bowmen_star_out_021",
		["type"] = "弓兵",
		["name"] = "预备弓兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "165",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["bowmen_star_out_031"] = {
		["id"] = "bowmen_star_out_031",
		["type"] = "弓兵",
		["name"] = "初阶弓兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "166",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["bowmen_star_out_041"] = {
		["id"] = "bowmen_star_out_041",
		["type"] = "弓兵",
		["name"] = "中阶弓兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "167",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["bowmen_star_out_051"] = {
		["id"] = "bowmen_star_out_051",
		["type"] = "弓兵",
		["name"] = "高阶弓兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "168",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["crossbowman_star_out_011"] = {
		["id"] = "crossbowman_star_out_011",
		["type"] = "弩兵",
		["name"] = "实习弩兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "169",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["crossbowman_star_out_021"] = {
		["id"] = "crossbowman_star_out_021",
		["type"] = "弩兵",
		["name"] = "预备弩兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "170",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["crossbowman_star_out_031"] = {
		["id"] = "crossbowman_star_out_031",
		["type"] = "弩兵",
		["name"] = "初阶弩兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "171",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["crossbowman_star_out_041"] = {
		["id"] = "crossbowman_star_out_041",
		["type"] = "弩兵",
		["name"] = "中阶弩兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "172",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["crossbowman_star_out_051"] = {
		["id"] = "crossbowman_star_out_051",
		["type"] = "弩兵",
		["name"] = "高阶弩兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "173",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["musketeer_star_out_011"] = {
		["id"] = "musketeer_star_out_011",
		["type"] = "火枪兵",
		["name"] = "实习火枪兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "174",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["musketeer_star_out_021"] = {
		["id"] = "musketeer_star_out_021",
		["type"] = "火枪兵",
		["name"] = "预备火枪兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "175",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["musketeer_star_out_031"] = {
		["id"] = "musketeer_star_out_031",
		["type"] = "火枪兵",
		["name"] = "初阶火枪兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "176",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["musketeer_star_out_041"] = {
		["id"] = "musketeer_star_out_041",
		["type"] = "火枪兵",
		["name"] = "中阶火枪兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "177",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["musketeer_star_out_051"] = {
		["id"] = "musketeer_star_out_051",
		["type"] = "火枪兵",
		["name"] = "高阶火枪兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "178",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["artillery_star_out_011"] = {
		["id"] = "artillery_star_out_011",
		["type"] = "炮兵",
		["name"] = "实习炮兵",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "179",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["artillery_star_out_021"] = {
		["id"] = "artillery_star_out_021",
		["type"] = "炮兵",
		["name"] = "预备炮兵",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "180",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["artillery_star_out_031"] = {
		["id"] = "artillery_star_out_031",
		["type"] = "炮兵",
		["name"] = "初阶炮兵",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "181",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["artillery_star_out_041"] = {
		["id"] = "artillery_star_out_041",
		["type"] = "炮兵",
		["name"] = "中阶炮兵",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "182",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["artillery_star_out_051"] = {
		["id"] = "artillery_star_out_051",
		["type"] = "炮兵",
		["name"] = "高阶炮兵",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "183",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["siege_star_out_011"] = {
		["id"] = "siege_star_out_011",
		["type"] = "攻城器",
		["name"] = "实习攻城器",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "184",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["siege_star_out_021"] = {
		["id"] = "siege_star_out_021",
		["type"] = "攻城器",
		["name"] = "预备攻城器",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "185",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["siege_star_out_031"] = {
		["id"] = "siege_star_out_031",
		["type"] = "攻城器",
		["name"] = "初阶攻城器",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "186",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["siege_star_out_041"] = {
		["id"] = "siege_star_out_041",
		["type"] = "攻城器",
		["name"] = "中阶攻城器",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "187",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["siege_star_out_051"] = {
		["id"] = "siege_star_out_051",
		["type"] = "攻城器",
		["name"] = "高阶攻城器",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "188",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
	["blade_hunter_star_out_011"] = {
		["id"] = "blade_hunter_star_out_011",
		["type"] = "旋刃猎手",
		["name"] = "实习旋刃猎手",
		["star"] = 1,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "189",
			},
		},
		["atk_coe"] = 1.22,
		["def_coe"] = 1.22,
		["hp_coe"] = 1.22,
		["mdef_coe"] = 1.22,
		["speed_coe"] = 1.22,
		["hit_coe"] = 1.22,
		["flee_coe"] = 1.22,
		["cri_coe"] = 1.22,
		["anticri_coe"] = 1.22,
		["crihurt_coe"] = 1,
	},
	["blade_hunter_star_out_021"] = {
		["id"] = "blade_hunter_star_out_021",
		["type"] = "旋刃猎手",
		["name"] = "预备旋刃猎手",
		["star"] = 2,
		["stage"] = 1,
		["exp"] = 2500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "190",
			},
		},
		["atk_coe"] = 1.24,
		["def_coe"] = 1.24,
		["hp_coe"] = 1.24,
		["mdef_coe"] = 1.24,
		["speed_coe"] = 1.24,
		["hit_coe"] = 1.24,
		["flee_coe"] = 1.24,
		["cri_coe"] = 1.24,
		["anticri_coe"] = 1.24,
		["crihurt_coe"] = 1,
	},
	["blade_hunter_star_out_031"] = {
		["id"] = "blade_hunter_star_out_031",
		["type"] = "旋刃猎手",
		["name"] = "初阶旋刃猎手",
		["star"] = 3,
		["stage"] = 1,
		["exp"] = 3000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "191",
			},
		},
		["atk_coe"] = 1.26,
		["def_coe"] = 1.26,
		["hp_coe"] = 1.26,
		["mdef_coe"] = 1.26,
		["speed_coe"] = 1.26,
		["hit_coe"] = 1.26,
		["flee_coe"] = 1.26,
		["cri_coe"] = 1.26,
		["anticri_coe"] = 1.26,
		["crihurt_coe"] = 1,
	},
	["blade_hunter_star_out_041"] = {
		["id"] = "blade_hunter_star_out_041",
		["type"] = "旋刃猎手",
		["name"] = "中阶旋刃猎手",
		["star"] = 4,
		["stage"] = 1,
		["exp"] = 3500,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "192",
			},
		},
		["atk_coe"] = 1.28,
		["def_coe"] = 1.28,
		["hp_coe"] = 1.28,
		["mdef_coe"] = 1.28,
		["speed_coe"] = 1.28,
		["hit_coe"] = 1.28,
		["flee_coe"] = 1.28,
		["cri_coe"] = 1.28,
		["anticri_coe"] = 1.28,
		["crihurt_coe"] = 1,
	},
	["blade_hunter_star_out_051"] = {
		["id"] = "blade_hunter_star_out_051",
		["type"] = "旋刃猎手",
		["name"] = "高阶旋刃猎手",
		["star"] = 5,
		["stage"] = 1,
		["exp"] = 4000,
		["require"] = {
			[1] = {
				[1] = "gold",
				[2] = "10",
			},
			[2] = {
				[1] = "gem",
				[2] = "193",
			},
		},
		["atk_coe"] = 1.3,
		["def_coe"] = 1.3,
		["hp_coe"] = 1.3,
		["mdef_coe"] = 1.3,
		["speed_coe"] = 1.3,
		["hit_coe"] = 1.3,
		["flee_coe"] = 1.3,
		["cri_coe"] = 1.3,
		["anticri_coe"] = 1.3,
		["crihurt_coe"] = 1,
	},
}
