return {
	[1] = {
		["id"] = 1,
		["slot_min"] = 0,
		["slot_max"] = 1,
		["enchance0_num"] = 1,
		["enchance3_num"] = 1,
		["enchance6_num"] = 2,
		["enchance9_num"] = 3,
		["enchance12_num"] = 4,
		["enchance15_num"] = 4,
		["enchance18_num"] = 5,
	},
	[2] = {
		["id"] = 2,
		["slot_min"] = 1,
		["slot_max"] = 2,
		["enchance0_num"] = 2,
		["enchance3_num"] = 2,
		["enchance6_num"] = 2,
		["enchance9_num"] = 3,
		["enchance12_num"] = 4,
		["enchance15_num"] = 4,
		["enchance18_num"] = 5,
	},
	[3] = {
		["id"] = 3,
		["slot_min"] = 1,
		["slot_max"] = 3,
		["enchance0_num"] = 3,
		["enchance3_num"] = 3,
		["enchance6_num"] = 3,
		["enchance9_num"] = 3,
		["enchance12_num"] = 4,
		["enchance15_num"] = 4,
		["enchance18_num"] = 5,
	},
	[4] = {
		["id"] = 4,
		["slot_min"] = 2,
		["slot_max"] = 4,
		["enchance0_num"] = 4,
		["enchance3_num"] = 4,
		["enchance6_num"] = 4,
		["enchance9_num"] = 4,
		["enchance12_num"] = 4,
		["enchance15_num"] = 4,
		["enchance18_num"] = 5,
	},
	[5] = {
		["id"] = 5,
		["slot_min"] = 3,
		["slot_max"] = 4,
		["enchance0_num"] = 5,
		["enchance3_num"] = 5,
		["enchance6_num"] = 5,
		["enchance9_num"] = 5,
		["enchance12_num"] = 5,
		["enchance15_num"] = 5,
		["enchance18_num"] = 5,
	},
}
